### ISSUE TITLE
LDAP requests failing with pyasn1v0.2.3

### ISSUE THREAD

**Issue by the-useless-one** [CoreSecurity/impacket#259]
Hi @asolino!

From [this thread](https://github.com/the-useless-one/pywerview/issues/20), it appears that impacket's LDAP implementation is not compatible with pyasn1v0.2.3.

When I try to issue an LDAP request with pyasn1v0.2.3, I get the following error:

```
$ ./pywerview.py get-netuser -t 10.0.0.1 -u root -p toor --username root
Traceback (most recent call last):
  File "./pywerview.py", line 24, in <module>
    main()
  File "/home/yme/tools/pywerview/pywerview/cli/main.py", line 449, in main
    results = args.func(**parsed_args)
  File "/home/yme/tools/pywerview/pywerview/cli/helpers.py", line 46, in get_netuser
    custom_filter=custom_filter)
  File "/home/yme/tools/pywerview/pywerview/requester.py", line 134, in wrapper
    return f(*args, **kwargs)
  File "/home/yme/tools/pywerview/pywerview/functions/net.py", line 71, in get_netuser
    return self._ldap_search(user_search_filter, adobj.User)
  File "/home/yme/tools/pywerview/pywerview/requester.py", line 96, in _ldap_search
    size=1000)
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldapasn1.py", line 582, in __init__
    self['controlType'] = CONTROL_PAGEDRESULTS
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/univ.py", line 1945, in __setitem__
    self.setComponentByName(idx, value)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/univ.py", line 2037, in setComponentByName
    self._componentType.getPositionByName(name), value, verifyConstraints, matchTags, matchConstraints
  File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldapasn1.py", line 552, in setComponentByPosition
    matchConstraints=matchConstraints)
TypeError: setComponentByPosition() got an unexpected keyword argument 'exactTypes'
```

However, the same request works with pyasn1v0.1.9. Do you know what the problem might be? Is impacket incompatible with pyasn1v0.2.3? Let me know if you need more information. Thanks!

Cheers,

Y

**Comment by asolino** [comment]
Adding @kacpern since he helped a lot last time there was an issue with pyasn1.

**Comment by asolino** [comment]
Ok.. looks like `univ.Sequence.setComponentByPosition()` signature got [changed](https://github.com/etingof/pyasn1/commit/a64b2a0c501437933ebc6b36032f097a2e6e4dd9#diff-2069cefef62bdc2d76dc303cdeb9a156L2290).

Can you guys remove [this](https://github.com/CoreSecurity/impacket/blob/master/impacket/ldap/ldapasn1.py#L538) line and give it a try?

**Comment by asolino** [comment]
Please check https://github.com/CoreSecurity/impacket/commit/4757b0d225f0bcab17195decccab11a45d1c2ea5 and close the issue if everything's working.

**Comment by the-useless-one** [comment]
It seems to be working (even though I didn't test all the side effects of your commit). Awesome, as usual :)

Closing, thank you!

Y
