### ISSUE TITLE
AttributeError: SMBTransport instance has no attribute 'setRemoteHost' when attempting to connect

### ISSUE THREAD

**Issue by zaggynl** [CoreSecurity/impacket#177]
commandline used:
python psexec.py 192.168.1.210 notepad.exe
Impacket v0.9.15 - Copyright 2002-2016 Core Security Technologies

Traceback (most recent call last):
  File "psexec.py", line 479, in <module>
    executer.run(remoteName, options.target_ip)
  File "psexec.py", line 81, in run
    rpctransport.setRemoteHost(remoteHost)
AttributeError: SMBTransport instance has no attribute 'setRemoteHost'

version used: https://github.com/CoreSecurity/impacket/releases/download/impacket_0_9_15/impacket-0.9.15.tar.gz

**Comment by asolino** [comment]
Hey @zaggynl 

Looks like you're using the `psexec.py` version from trunk (`0.9.16-dev`) instead of the one that works with `0.9.15`.

`SMBTransport.setRemoteHost()` was added after `0.9.15` version was released ([commit here] (https://github.com/CoreSecurity/impacket/commit/ef2ed82977ac746fe44ac19356f9c923d3d67215#diff-261110502c4bc6e3e5882fdb7067f4f2R158)). You cannot use the current psexec.py version with 0.9.15.

You have two options:
1. `git pull` master and install the dev version `0.9.16-dev`
2. Install `0.9.15` and use the `psexec.py` for that specific version. It is bundled inside the package or can also be located [here](https://github.com/CoreSecurity/impacket/blob/impacket_0_9_15/examples/psexec.py)

I'm closing this issue, if there's anything wrong please open it again.
